version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    network_mode: "bridge"

  zeppelin:
    image: apache/zeppelin:0.8.1
    ports:
      - 9080:8080
#      - 9443:8443
    volumes:
      - ./notebook:/notebook
      - ./data:/data
      - ./interpreter.json:/zeppelin/conf/interpreter.json
    environment:
      ZEPPELIN_NOTEBOOK_DIR: /notebook
      ZEPPELIN_JAVA_OPTS:
        -Dspark.driver.memory=2g
        -Dspark.executor.memory=4g
    links:
      - mysql
      - elasticsearch
    network_mode: "bridge"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: elasticsearch1
    environment:
      - node.name=elasticsearch1
      - cluster.initial_master_nodes=elasticsearch1
      - cluster.name=docker-cluster
#      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    volumes:
#      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    network_mode: "bridge"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://elasticsearch1:9200/
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    network_mode: "bridge"
