version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    network_mode: "bridge"

  zeppelin:
    image: apache/zeppelin:0.8.1
    ports:
      - 9080:8080
#      - 9443:8443
    volumes:
      - ./notebook:/notebook
      - ./data:/data
      - ./interpreter.json:/zeppelin/conf/interpreter.json
    environment:
      ZEPPELIN_NOTEBOOK_DIR: /notebook
      ZEPPELIN_JAVA_OPTS:
        -Dspark.driver.memory=2g
        -Dspark.executor.memory=4g
    links:
      - mysql
    network_mode: "bridge"